{% set name = "salesforce-merlion" %}
{% set version = "2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eeef166fa618ea7fe8ba11ee790c85742d07287bda7a6dcff912ec4279ea6219

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7.0
  run:
    - cython
    - dill
    - gitpython
    - lightgbm
    - matplotlib-base
    - numpy >=1.21
    - packaging
    - pandas >=1.1.0
    - plotly >=4.13
    - prophet >=1.1
    - py4j
    - python >=3.7.0
    - scikit-learn >=0.22
    - scipy >=1.6.0
    - statsmodels >=0.12.2
    - tqdm

test:
  imports:
    - merlion
    - merlion.evaluate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/salesforce/Merlion
  doc_url: https://opensource.salesforce.com/Merlion/latest/index.html
  summary: A Machine Learning Framework for Time Series Intelligence
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Merlion is a Python library for time series intelligence. It
     features a unified interface for many commonly used models and
     datasets for anomaly detection and forecasting on both univariate
     and multivariate time series, along with standard pre-processing
     and post-processing layers. It has several modules to improve
     ease-of-use, including visualization, anomaly score calibration to
     improve interpetability, AutoML for hyperparameter tuning and model
     selection, and model ensembling. Merlion also provides a unique
     evaluation framework that simulates the live deployment and
     re-training of a model in production. This library aims to provide
     engineers and researchers a one-stop solution to rapidly develop
     models for their specific time series needs, and benchmark them
     across multiple time series datasets.

extra:
  recipe-maintainers:
    - thewchan
