{% set name = "salesforce-merlion" %}
{% set version = "1.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 174febbe07ff33b553ab1785529c68b0ea22761a24771b7d4479702c938beef0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cmdstanpy
    - dill
    - fbprophet
    - gitpython
    - llvm-openmp
    - lightgbm
    - matplotlib-base
    - numpy !=1.18
    - jpype1 ==1.0.2
    - pandas >=1.1.0
    - plotly >=4.13
    - pystan <3.0
    - python >=3.6
    - pytorch >=1.1.0
    - scikit-learn >=0.22
    - scipy >=1.5.0
    - setuptools-git
    - statsmodels >=0.12.2
    - tqdm

test:
  imports:
    - merlion
    - merlion.evaluate
  commands:
    - pip list | grep -E '{{ name }}\s+{{ version }}'
  requires:
    - pip

about:
  home: https://github.com/salesforce/Merlion
  doc_url: https://opensource.salesforce.com/Merlion/latest/index.html
  summary: A Machine Learning Framework for Time Series Intelligence
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    Merlion is a Python library for time series intelligence. It
     features a unified interface for many commonly used models and
     datasets for anomaly detection and forecasting on both univariate
     and multivariate time series, along with standard pre-processing
     and post-processing layers. It has several modules to improve
     ease-of-use, including visualization, anomaly score calibration to
     improve interpetability, AutoML for hyperparameter tuning and model
     selection, and model ensembling. Merlion also provides a unique
     evaluation framework that simulates the live deployment and
     re-training of a model in production. This library aims to provide
     engineers and researchers a one-stop solution to rapidly develop
     models for their specific time series needs, and benchmark them
     across multiple time series datasets.

extra:
  recipe-maintainers:
    - thewchan
